import React, { useEffect, useState, useRef } from 'react'
import TableCard from '../components/TableCard'
import UniverseBadge from '../components/UniverseBadge'

export default function FnoHistory() {
  const [recs, setRecs] = useState([])
  const [loading, setLoading] = useState(true)
  const [badgeCache, setBadgeCache] = useState({})
  
  // Filtering States
  const [symbolFilter, setSymbolFilter] = useState('')
  const [statusFilter, setStatusFilter] = useState('')
  const [strategyFilter, setStrategyFilter] = useState('')
  const [page, setPage] = useState(0)

  const fetchHistory = async () => {
    setLoading(true)
    try {
      let url = `/api/fno/recommendations/history?limit=20&offset=${page * 20}`
      if (symbolFilter) url += `&symbol=${symbolFilter}`
      if (statusFilter) url += `&status=${statusFilter}`
      if (strategyFilter) url += `&strategy=${strategyFilter}`

      const response = await fetch(url)
      const data = await response.json()
      setRecs(data)
      
      // Load universe badges for unique symbols (presentation-only lookup)
      const uniqueSymbols = [...new Set(data.map(r => r.symbol))]
      const badges = {}
      await Promise.all(
        uniqueSymbols.map(async (sym) => {
          try {
            const res = await fetch(`/api/fno/universe-badges?symbol=${sym}`)
            const json = await res.json()
            badges[sym] = json.universes || []
          } catch { badges[sym] = [] }
        })
      )
      setBadgeCache(prev => ({ ...prev, ...badges }))
    } catch (e) {
      console.error(e)
    } finally {
      setLoading(false)
    }
  }

  useEffect(() => {
    fetchHistory()
  }, [symbolFilter, statusFilter, strategyFilter, page])

  const handleUpdateStatus = async (uuid, newStatus) => {
    try {
      await fetch(`/api/fno/recommendations/${uuid}/status?status=${newStatus}`, {
        method: 'PATCH'
      })
      fetchHistory()
    } catch (e) {
      console.error(e)
    }
  }

  return (
    <div className="fno-history-page" style={{ padding: '32px' }}>
      
      {/* Header */}
      <div style={{ marginBottom: '24px' }}>
        <h1 style={{ fontSize: '1.8rem', fontWeight: '800' }}>F&O Recommendation History</h1>
        <div style={{ color: 'var(--text-muted)', fontSize: '0.85rem', marginTop: '4px' }}>
          Permanent Audit Ledger of all Volatility Risk Premium spreads generated by strategy engines.
        </div>
      </div>

      {/* Filter Bar */}
      <div className="card" style={{ padding: '16px 20px', marginBottom: '24px', display: 'flex', gap: '16px', flexWrap: 'wrap', alignItems: 'center' }}>
        
        <div>
          <label style={{ display: 'block', fontSize: '0.68rem', color: 'var(--text-muted)', marginBottom: '4px', textTransform: 'uppercase' }}>Index Underlier</label>
          <select 
            value={symbolFilter} 
            onChange={(e) => { setSymbolFilter(e.target.value); setPage(0); }}
            style={{ background: 'var(--bg-card-header)', border: '1px solid var(--border)', padding: '6px 12px', borderRadius: '4px', color: 'var(--text-primary)', fontSize: '0.8rem' }}
          >
            <option value="">All Indices</option>
            <option value="NIFTY">NIFTY</option>
            <option value="BANKNIFTY">BANKNIFTY</option>
            <option value="SENSEX">SENSEX</option>
            <option value="FINNIFTY">FINNIFTY</option>
            <option value="MIDCPNIFTY">MIDCPNIFTY</option>
          </select>
        </div>

        <div>
          <label style={{ display: 'block', fontSize: '0.68rem', color: 'var(--text-muted)', marginBottom: '4px', textTransform: 'uppercase' }}>Lifecycle Status</label>
          <select 
            value={statusFilter} 
            onChange={(e) => { setStatusFilter(e.target.value); setPage(0); }}
            style={{ background: 'var(--bg-card-header)', border: '1px solid var(--border)', padding: '6px 12px', borderRadius: '4px', color: 'var(--text-primary)', fontSize: '0.8rem' }}
          >
            <option value="">All Statuses</option>
            <option value="READY">READY</option>
            <option value="OPEN">OPEN</option>
            <option value="ACTIVE">ACTIVE</option>
            <option value="CLOSED">CLOSED</option>
            <option value="IGNORED">IGNORED</option>
          </select>
        </div>

        <div>
          <label style={{ display: 'block', fontSize: '0.68rem', color: 'var(--text-muted)', marginBottom: '4px', textTransform: 'uppercase' }}>Strategy Engine</label>
          <select 
            value={strategyFilter} 
            onChange={(e) => { setStrategyFilter(e.target.value); setPage(0); }}
            style={{ background: 'var(--bg-card-header)', border: '1px solid var(--border)', padding: '6px 12px', borderRadius: '4px', color: 'var(--text-primary)', fontSize: '0.8rem' }}
          >
            <option value="">All Strategies</option>
            <option value="vrp_harvester">VRP Harvester</option>
          </select>
        </div>

      </div>

      {/* Grid List */}
      <div className="card">
        {loading ? (
          <div style={{ padding: '40px', textAlign: 'center' }}>
            <div className="loader" style={{ margin: '0 auto' }} />
          </div>
        ) : recs.length === 0 ? (
          <div style={{ padding: '40px', textAlign: 'center', color: 'var(--text-muted)' }}>
            No historical records found matching current query parameters.
          </div>
        ) : (
          <TableCard
            title=""
            headers={[
              'Generation Time', 'Symbol', 'Strategy', 'Structure', 
              'Credit', 'Max Risk', 'Confidence', 'Status', 'Audit Actions'
            ]}
            data={recs}
            renderRow={(r, idx) => (
              <tr key={idx} style={{ fontSize: '0.8rem' }}>
                <td style={{ fontFamily: 'var(--font-mono)' }}>
                  {new Date(r.timestamp).toLocaleString()}
                </td>
                <td style={{ fontWeight: '700' }}>
                  <div style={{ display: 'flex', alignItems: 'center', gap: '6px', flexWrap: 'wrap' }}>
                    {r.symbol}
                    <UniverseBadge universes={badgeCache[r.symbol]} size="tiny" />
                  </div>
                </td>
                <td>
                  <span style={{ color: 'var(--accent-blue-bright)', fontWeight: '600' }}>
                    {r.structure.vehicle}
                  </span>
                  <div style={{ fontSize: '0.65rem', color: 'var(--text-muted)' }}>
                    Ver: {r.strategy_version}
                  </div>
                </td>
                <td style={{ fontSize: '0.72rem' }}>
                  C: {r.structure.shortCall} / P: {r.structure.shortPut}
                </td>
                <td className="text-green">₹ {r.net_credit.toLocaleString()}</td>
                <td className="text-red">₹ {r.max_risk.toLocaleString()}</td>
                <td style={{ fontWeight: '700', fontFamily: 'var(--font-mono)', color: 'var(--accent-green)' }}>
                  {r.confidence_score}%
                </td>
                <td>
                  <span 
                    className="badge-status" 
                    style={{ 
                      fontSize: '0.7rem', 
                      background: r.structure.status === 'CLOSED' ? 'rgba(255,255,255,0.05)' : r.structure.status === 'ACTIVE' ? 'rgba(34,197,94,0.15)' : 'rgba(99,155,255,0.15)',
                      color: r.structure.status === 'CLOSED' ? 'var(--text-muted)' : r.structure.status === 'ACTIVE' ? 'var(--accent-green)' : 'var(--accent-blue-bright)'
                    }}
                  >
                    {r.structure.status}
                  </span>
                </td>
                <td>
                  <div style={{ display: 'flex', gap: '8px' }}>
                    <select
                      value={r.structure.status}
                      onChange={(e) => handleUpdateStatus(r.recommendation_uuid, e.target.value)}
                      style={{ background: 'var(--bg-card)', border: '1px solid var(--border)', fontSize: '0.72rem', padding: '2px 4px', borderRadius: '3px', color: 'var(--text-primary)' }}
                    >
                      <option value="READY">READY</option>
                      <option value="OPEN">OPEN</option>
                      <option value="ACTIVE">ACTIVE</option>
                      <option value="CLOSED">CLOSED</option>
                      <option value="IGNORED">IGNORED</option>
                    </select>
                    <a
                      href={`/fno-analysis/${r.symbol}?rec_id=${r.recommendation_uuid}`}
                      target="_blank"
                      rel="noopener noreferrer"
                      className="btn btn-ghost"
                      style={{ fontSize: '0.72rem', padding: '2px 6px', textDecoration: 'none', color: 'var(--accent-blue-bright)' }}
                    >
                      Audit
                    </a>
                  </div>
                </td>
              </tr>
            )}
          />
        )}
      </div>

      {/* Pagination Bar */}
      <div style={{ display: 'flex', justifyContent: 'flex-end', gap: '8px', marginTop: '16px' }}>
        <button 
          className="btn btn-ghost" 
          disabled={page === 0} 
          onClick={() => setPage(p => p - 1)}
          style={{ fontSize: '0.8rem' }}
        >
          Previous
        </button>
        <button 
          className="btn btn-ghost" 
          disabled={recs.length < 20} 
          onClick={() => setPage(p => p + 1)}
          style={{ fontSize: '0.8rem' }}
        >
          Next
        </button>
      </div>

    </div>
  )
}
